name: Bundle Pupil Core

on:
  pull_request:
  push:
    branches:
      - develop
    tags:
      - "**"
  workflow_dispatch:

jobs:
  Bundle:
    name: Bundle ${{ matrix.platform }}
    strategy:
      fail-fast: False
      matrix:
        platform:
          - windows-latest
          - macOS-11
          - ubuntu-latest
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Install Pupil Core dependencies
        env:
          ARCHFLAGS: "-arch x86_64"
        run: |
          python -m pip install -U pip wheel
          python -m pip install -r requirements.txt PyInstaller
      - name: Bundle on Windows
        if: runner.os == 'Windows'
        run: .\reproducible_build.ps1
        shell: powershell
        working-directory: deployment
      - name: Import macOS codesign certificates
        if: runner.os == 'macOS'
        uses: apple-actions/import-codesign-certs@v1
        with:
          p12-file-base64: ${{ secrets.MACOS_CERTIFICATE }}
          p12-password: ${{ secrets.MACOS_CERTIFICATE_PWD }}
      - name: Bundle on Unix
        if: runner.os != 'Windows'
        run: ./reproducible_build.sh
        working-directory: deployment
        env:
          MACOS_CODESIGN_IDENTITY: ${{ secrets.MACOS_CODESIGN_IDENTITY }}
      - name: Upload build as artifact
        uses: actions/upload-artifact@v3
        with:
          name: bundle-${{ matrix.platform }}
          path: |
            deployment/*.rar
            deployment/*.dmg
            deployment/*.zip
